name: guile
visible_name: Guile 2.0
version: "2.0.11"
apparmor_profile: straitjacket/interpreter/guile
filename: source.scm
docker_image: straitjacket-guile

tests:
  simple:
    source: |
      (begin (display "hi from guile") (newline))
    stdout: "\\Ahi from guile\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  apparmor:
    source: |
      (with-input-from-file "/etc/passwd" (lambda ()
        (define loop (lambda (token)
          (if (not (eof-object? token))
            (begin (display token) (newline) (loop (read))))))
            (loop (read))))
    stdout: "\\A\\z"
    stderr: "ERROR: In procedure open-file: Permission denied: \"/etc/passwd\""
    exitstatus: 1

  rlimit:
    source: |
      (begin (display (make-string 1073741824)) (newline))
    stdout: "\\A\\z"
    stderr: "GC Warning: Out of Memory!"
    exitstatus: 139
