name: fortran
visible_name: Fortran
version: "F2008"
compiler_profile: straitjacket/compiler/gfortran
apparmor_profile: straitjacket/compiled/gfortran
filename: source.f08
docker_image: straitjacket/lang-fortran

file_extensions:
  - f08
  - f90
  - fortran

tests:
  simple:
    source: |
      INTEGER :: num
      INTEGER :: ios

      ! Start the read block
      DO
        READ(*,*, END=999, IOSTAT=ios) num
        IF (ios == 0) THEN
          WRITE(*, '(I0)') num*2
        END IF
      END DO

      999 CONTINUE
        STOP

      END
    stdin:  "1\n2\n3\n"
    stdout: "\\A2\n4\n6\n\\z"
    stderr: "\\A\\z"
    exitstatus: 0

  apparmor:
    source: |
      program apparmortest
      open(unit=1, file="/etc/hosts")
      read(1, *) x, y
      close(1)
      end
    stdout: "\\A\\z"
    stderr: "Permission denied trying to open file '/etc/hosts'"
    exitstatus: 2

  rlimit:
    source: |
      program rlimittest
      print *, "starting allocation"
      call rlimit(1073741824)
      print *, "finished allocation"
      end

      subroutine rlimit(ilen)
      implicit double precision (a-h,o-z), integer (i-n)
      dimension iarray(ilen), array(ilen)
      parameter (ZERO = 0.0d0)
      do 100 i=1,ilen
         iarray(i) = i
         array(i) = ZERO
      100 continue
      end
    stdout: "\\A starting allocation\\n\\z"
    stderr:
    exitstatus: 141
